### PR TITLE
feat: add USB device output

### PR DESCRIPTION
**Pull request by ahoneybun**
I would like to use this crate in the future (and for the other pages to use crates as well):

https://docs.rs/cyme/1.7.0/cyme/

But this is a starting point!

### CODE REVIEW

**Review by sungsphinx — APPROVED** [review]
Other than the PCI and USB pages having the same icon, this LGTM.

**Comment by ahoneybun** [comment]
@sungsphinx yea I need to get a list of available icons and perhaps swap that.

**Comment by ahoneybun** [comment]
That icon might be better.

**Review by edfloreshz — COMMENTED** [review]
Little bit late but LGTM

**Pull request merged**
